services:
  pdflight:
    build: .
    # image: ghcr.io/mirkocompagnoni/pdflight:latest
    container_name: pdflight
    ports:
      - "9070:8080"
    environment:
      - PDFLIGHT_MAX_MB=30
      - PDFLIGHT_DEFAULT_PRESET=ebook
      - PDFLIGHT_OCR_DEFAULT=0
    restart: unless-stopped
